# target position
pesat_msgs/FloatArray[] target_poses
# drone position
pesat_msgs/FloatArray[] drone_poses
# map
pesat_msgs/FloatArray environment_map
---
# probabilistic map
pesat_msgs/FloatArray probabilistic_map
