dynamic_avoidance:
    camera_base_link: bebop2/camera_base_link
    camera_optical_link: bebop2/camera_base_optical_link
    base_link: bebop2/base_link
    map: map
    cmd_vel_topic: bebop2/cmd_vel
    state_change_topic: /bebop2/dronet/state_change
    dronet_cmd_vel_topic: /bebop2/dronet/cmd_vel
    cnn_prediction_topic: /cnn_out/predictions
    low_bound: 0.7
