environment_configuration:
  map:
    frame: map
    obstacles_file: /home/patik/Diplomka/dp_ws/src/pesat_resources/worlds/sworld-500-0_0996-1-f--1-y-13_18_23/sworld-500-0_0996-1-f--1-y-13_18_23.json
    section_file: /home/patik/Diplomka/dp_ws/src/pesat_resources/worlds/sworld-500-0_0996-1-f--1-y-13_18_23/section_file.json
    size: 10
  world:
    path: $(find pesat_resources)/worlds
    name: box_world
  properties:
    extra_localization: false
  watchdog:
    cameras_file: .
    camera_shot_topic: "/cctv/shot"
    camera_registration_service: "/cctv/registration"
    camera_update_topic: "/cctv/update"
    camera_notification_topic: "/cctv/notifications"
    camera_switch_topic: "/cctv/switch"
  init_positions:
    target:
      x: -139.01939149171113
      y: 236.13914961397649
    drone:
      x: 123.61506480753422
      y: 248.47501769691706
      z: 4
    