track:
    track_timeout: 10
    center_target_limit: 100
    max_camera_vel: 0.04
    max_linear_vel: 0.1
    max_angular_vel: 0.08
    distance_limit: 0.01
    yaw_limit: 0.001
    camera_limit: 0.001
    camera_max_angle: 30
    history_query_length: 8
    correction_timeout: 1
    pmap_size: 680
    pmap_center:
        x: 0
        y: 0
    group_name: 'Bebop2'
    namespace: ''
    eef_step: 0.01
    jump_threshold: 0.0
    camera_base_link: bebop2/camera_base_link
    camera_optical_link: bebop2/camera_base_optical_link
    base_link: bebop2/base_link
    map: map
    target_position: tarloc/target
    target_position_predictions_service: target_position_predictions
    goal_drone_positions_service: goal_drone_positions
    state_change_topic: /bebop2/dronet/state_change
    dronet_cmd_vel_topic: /bebop2/dronet/cmd_vel
    cnn_prediction_topic: /cnn_out/predictions
    target_information_topic: /target/information
    image_width: 856
    image_height: 480
    position_epsilon: 1  # meters
    angle_epsilon: 5
    goal_position_epsilon: 1  # meters
    goal_angle_epsilon_divider: 9.0
    goal_angle_camera_epsilon_divider: 9.0
    history_position_deque_len: 1200
    obstacle_file: /home/patik/Diplomka/dp_ws/src/py_scripts/map_data.json
    planning_scene_topic: planning_scene
