track:
    track_timeout: 10
    center_target_limit: 100
    distance_limit: 0.01
    yaw_limit: 0.001
    camera_limit: 0.001
    camera_max_angle: 30
    history_query_length: 8
    correction_timeout: 1
    pmap_size: 680
    pmap_center:
        x: 0
        y: 0
    group_name: 'Bebop2'
    namespace: ''
    eef_step: 0.01
    jump_threshold: 0.0
    camera_base_link: bebop2/camera_base_link
    camera_optical_link: bebop2/camera_base_optical_link
    base_link: bebop2/base_link
    map: map
    target_position: tarloc/target
    target_position_predictions_service: target_position_predictions
    goal_drone_positions_service: goal_drone_positions
    position_epsilon: 1  # meters
    angle_epsilon: 5
    goal_position_epsilon: 1  # meters
    goal_angle_epsilon_divider: 9.0
    goal_angle_camera_epsilon_divider: 9.0
    history_position_deque_len: 1200
    obstacles_file: /home/patik/Diplomka/dp_ws/src/py_scripts/map_data.json
    planning_scene_topic: planning_scene
    launch_topic: "tracker/launch"
    next_position_service: "tracker/next_position"
    target_size:
        x: 428
        y: 240
