bebop2:
  controller:
    state:
      type: joint_state_controller/JointStateController
      publish_rate: 50
    velocity:
      X_AXIS:
        type: position_controllers/JointVelocityController
        joint: bebop2/camera_rotator_base_joint
        pid: {p: 10.0, i: 0.0, d: 1.0}
      Y_AXIS:
        type: position_controllers/JointVelocityController
        joint: bebop2/camera_rotator_base_joint
        pid: {p: 10.0, i: 0.0, d: 1.0}
      Z_AXIS:
        type: position_controllers/JointVelocityController
        joint: bebop2/camera_base_joint
        pid: {p: 10.0, i: 0.0, d: 1.0}
      YAW_ANGLE:
        type: position_controllers/JointVelocityController
        joint: bebop2/camera_base_joint
        pid: {p: 5.0, i: 2.0, d: 1.0}
      HORIZONTAL_ANGLE:
        type: position_controllers/JointVelocityController
        joint: bebop2/camera_base_joint
        pid: {p: 5.0, i: 2.0, d: 1.0}
      VERTICAL_ANGLE:
        type: position_controllers/JointVelocityController
        joint: bebop2/camera_rotator_base_joint
        pid: {p: 5.0, i: 2.0, d: 1.0}