Bebop2:
  controller:
    state:
      type: joint_state_controller/JointStateController
      publish_rate: 50
    position:
      X_AXIS:
        type: velocity_controllers/JointPositionController
        joint: YOUR_ROBOT_JOINT
        pid: {p: 10.0, i: 0.0, d: 1.0}
      Y_AXIS:
        type: velocity_controllers/JointPositionController
        joint: YOUR_ROBOT_JOINT
        pid: {p: 10.0, i: 0.0, d: 1.0}
      Z_AXIS:
        type: velocity_controllers/JointPositionController
        joint: YOUR_ROBOT_JOINT
        pid: {p: 10.0, i: 0.0, d: 1.0}
      YAW_ANGLE:
        type: velocity_controllers/JointPositionController
        joint: YOUR_ROBOT_JOINT
        pid: {p: 5.0, i: 2.0, d: 1.0}
      HORIZONTAL_ANGLE:
        type: velocity_controllers/JointPositionController
        joint: YOUR_ROBOT_JOINT
        pid: {p: 5.0, i: 2.0, d: 1.0}
      VERTICAL_ANGLE:
        type: velocity_controllers/JointPositionController
        joint: YOUR_ROBOT_JOINT
        pid: {p: 5.0, i: 2.0, d: 1.0}